apiVersion: v1
kind: ConfigMap
metadata:
  name: stockmania-config
  namespace: stockmania
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_BASE_URL: "https://stockmania.yourdomain.com"
  INNGEST_DEV: "0"
  ALPACA_BASE_URL: "https://paper-api.alpaca.markets"
