import { getLatestSignals } from "@/features/signals/signal.actions";
import { SignalCard } from "@/components/SignalCard";
import { Zap } from "lucide-react";

export default async function SignalsPage() {
  const signals = await getLatestSignals(20);

  return (
    <div className="flex flex-col gap-8">
      <div className="flex items-center gap-3">
        <span className="icon-chip h-11 w-11">
          <Zap className="h-5 w-5" />
        </span>
        <div>
          <h1 className="page-title">AI Signals</h1>
          <p className="page-subtitle">
            AI-generated trading signals each market day. Not financial advice — always verify.
          </p>
        </div>
      </div>

      <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 px-4 py-3 text-xs leading-5 text-gray-400">
        Signals are informational context, not trade instructions. Check the evidence, freshness and your own risk limits before acting.
      </div>

      {signals.length === 0 ? (
        <div className="panel border-dashed p-12 text-center">
          <Zap className="mx-auto mb-4 h-10 w-10 text-gray-500" />
          <p className="text-gray-400 mb-2">No signals generated yet.</p>
          <p className="text-sm text-gray-600">
            Signals are generated each market day at 9:30 AM. You can also trigger one from any stock page.
          </p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {signals.map((signal) => (
              <SignalCard key={signal.id} signal={signal} />
            ))}
          </div>
          <p className="text-xs text-gray-600 text-center">
            Signals expire after 6 hours. Generated by Gemini AI using price data + news sentiment.
          </p>
        </>
      )}
    </div>
  );
}
