import { getLatestSignals } from "@/features/signals/signal.actions";
import { SignalCard } from "@/components/SignalCard";
import { Zap } from "lucide-react";

export default async function SignalsPage() {
  const signals = await getLatestSignals(20);

  return (
    <div className="flex flex-col gap-8">
      <div>
        <div className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-yellow-400" />
          <h1 className="text-2xl font-bold text-gray-100">AI Signals</h1>
        </div>
        <p className="mt-1 text-sm text-gray-500">
          AI-generated trading signals updated every market day. Not financial advice — always verify before trading.
        </p>
      </div>

      {signals.length === 0 ? (
        <div className="rounded-xl border border-dashed border-gray-700 p-12 text-center">
          <Zap className="mx-auto h-10 w-10 text-gray-700 mb-4" />
          <p className="text-gray-400 mb-2">No signals generated yet.</p>
          <p className="text-sm text-gray-600">
            Signals are generated each market day at 9:30 AM. You can also trigger one from any stock page.
          </p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {signals.map((signal) => (
              <SignalCard key={signal.id} signal={signal} />
            ))}
          </div>
          <p className="text-xs text-gray-600 text-center">
            Signals expire after 6 hours. Generated by Gemini AI using price data + news sentiment.
          </p>
        </>
      )}
    </div>
  );
}
